import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ptduc
 */





public class BMI extends javax.swing.JFrame {

    /**
     * Creates new form BMI
     */
    public BMI() {
        initComponents();
        jLabel8.setVisible(false);
        jButton2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        bmr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FITNESS INTAKE");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Age");

        jLabel5.setText("Gender");

        jLabel6.setText("Weight (lbs)");

        jLabel7.setText("Height (ft)");

        jButton1.setText("Calculate BMI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("BMI");

        jButton2.setText("Recommonded Ideal Weight");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        bmr.setText("Calculate BMR");
        bmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(bmr))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField5)
                                        .addComponent(jComboBox1, 0, 161, Short.MAX_VALUE)
                                        .addComponent(jTextField6))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton2)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bmr))
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        jLabel3.getAccessibleContext().setAccessibleName("Last Name");

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(Double.parseDouble(jTextField6.getText().toString())<4.6||Double.parseDouble(jTextField6.getText().toString())>6.0)
        {
             JOptionPane.showMessageDialog(null, "Height Must be in between 4.6 - 6.0", "InfoBox: " + "Error Message", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        double weightlbs=Double.parseDouble(jTextField5.getText());
        double weightkg=weightlbs*0.45359237;
        double feet = Double.parseDouble(jTextField6.getText());
        double height=feet/3.2808;
        double age = Double.parseDouble(jTextField3.getText());
        double result=weightkg/(height*height);
        double round=Math.round(result * 100.0) / 100.0;
        
        jLabel8.setVisible(true);
        jButton2.setVisible(true);
        
         if( round < 18.5)
        {
           jLabel8.setText("BMI: "+String.valueOf(round) +"\t    UnderWeight");
        }
        else if( round < 24.9)
        {
           jLabel8.setText("BMI: "+String.valueOf(round) +"\t    Normal Weight");
        }
        else if( round < 29.9)
        {
           jLabel8.setText("BMI: "+String.valueOf(round) +"\t    Over Weight");
        }
        else 
        {
           jLabel8.setText("BMI: "+String.valueOf(round) +"\t    Obese");
        }
        
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        double calc = 0.0;
        double weightlbs=Double.parseDouble(jTextField5.getText());
        double weightkg=weightlbs*0.45359237;
        double feet = Double.parseDouble(jTextField6.getText());
        double height=feet/3.2808;
        double age = Double.parseDouble(jTextField3.getText());
        double result=weightkg/(height*height);
        double round=Math.round(result * 100.0) / 100.0;
        feet = Double.parseDouble(jTextField6.getText());
        int minwgt,maxwgt;
        String gender=jComboBox1.getSelectedItem().toString();
        //new CalorieIntake(calc).setVisible(true);
        if(gender.equals("Male"))
        {
            
        if(feet==4.6)
        {
            minwgt=61;
            maxwgt=77;
        }
        else if(feet==4.7)
        {
            minwgt=66;
            maxwgt=86;
        }
        else if(feet==4.8)
        {
            minwgt=72;
            maxwgt=88;
        }
        else if(feet==4.9)
        {
            minwgt=77;
            maxwgt=97;
        }
        else if(feet==4.10)
        {
            minwgt=83;
            maxwgt=101;
        }
        else if(feet==4.11)
        {
            minwgt=88;
            maxwgt=110;
        }
        else if(feet==5.0)
        {
            minwgt=94;
            maxwgt=116;
        }
        else if(feet==5.1)
        {
            minwgt=99;
            maxwgt=121;
        }
        else if(feet==5.2)
        {
            minwgt=105;
            maxwgt=130;
        }
        else if(feet==5.3)
        {
            minwgt=110;
            maxwgt=134;
        }
        else if(feet==5.4)
        {
            minwgt=116;
            maxwgt=143;
        }
        else if(feet==5.5)
        {
            minwgt=121;
            maxwgt=150;
        }
        else if(feet==5.6)
        {
            minwgt=127;
            maxwgt=154;
        }
        else if(feet==5.7)
        {
            minwgt=132;
            maxwgt=163;
        }
        else if(feet==5.8)
        {
            minwgt=138;
            maxwgt=167;
        }
        else if(feet==5.9)
        {
            minwgt=141;
            maxwgt=176;
        }
        else if(feet==5.10)
        {
            minwgt=147;
            maxwgt=182;
        }
        else if(feet==5.11)
        {
            minwgt=154;
            maxwgt=187;
        }
        else
        {
            minwgt=158;
            maxwgt=196;
        }
        this.setVisible(false);
        new WeightRecommonded(minwgt,maxwgt,gender,Integer.parseInt(jTextField5.getText().toString())).setVisible(true);
        
        //new CalorieIntake(calc).setVisible(true);
        }
        
        //for girls
        else
        {
            
        
        if(feet==4.6)
        {
            minwgt=61;
            maxwgt=77;
        }
        else if(feet==4.7)
        {
            minwgt=66;
            maxwgt=81;
        }
        else if(feet==4.8)
        {
            minwgt=70;
            maxwgt=88;
        }
        else if(feet==4.9)
        {
            minwgt=77;
            maxwgt=92;
        }
        else if(feet==4.10)
        {
            minwgt=79;
            maxwgt=99;
        }
        else if(feet==4.11)
        {
            minwgt=86;
            maxwgt=103;
        }
        else if(feet==5.0)
        {
            minwgt=88;
            maxwgt=110;
        }
        else if(feet==5.1)
        {
            minwgt=94;
            maxwgt=114;
        }
        else if(feet==5.2)
        {
            minwgt=99;
            maxwgt=121;
        }
        else if(feet==5.3)
        {
            minwgt=103;
            maxwgt=125;
        }
        else if(feet==5.4)
        {
            minwgt=108;
            maxwgt=132;
        }
        else if(feet==5.5)
        {
            minwgt=112;
            maxwgt=136;
        }
        else if(feet==5.6)
        {
            minwgt=116;
            maxwgt=143;
        }
        else if(feet==5.7)
        {
            minwgt=121;
            maxwgt=147;
        }
        else if(feet==5.8)
        {
            minwgt=125;
            maxwgt=154;
        }
        else if(feet==5.9)
        {
            minwgt=130;
            maxwgt=158;
        }
        else if(feet==5.10)
        {
            minwgt=134;
            maxwgt=165;
        }
        else if(feet==5.11)
        {
            minwgt=138;
            maxwgt=169;
        }
        else
        {
            minwgt=143;
            maxwgt=176;
        } 
        new WeightRecommonded(minwgt,maxwgt,gender,Integer.parseInt(jTextField5.getText().toString())).setVisible(true);
        //new CalorieIntake(calc).setVisible(true);
        }
    }                                        

    private void bmrActionPerformed(java.awt.event.ActionEvent evt) {                                    
        double calc = 0.0;
        double weightlbs=Double.parseDouble(jTextField5.getText());
        double weightkg=weightlbs*0.45359237;
        double feet = Double.parseDouble(jTextField6.getText());
        double height=feet/3.2808;
        double fHeight = feet * 12;
        double age = Double.parseDouble(jTextField3.getText());
        double result=weightkg/(height*height);
        double round=Math.round(result * 100.0) / 100.0;
        feet = Double.parseDouble(jTextField6.getText());
        int minwgt,maxwgt;
        String gender=jComboBox1.getSelectedItem().toString();
        //new CalorieIntake(calc).setVisible(true);
        if(gender.equals("Male")){
            calc = 66 + (6.23 * weightlbs) + (12.7 * fHeight) -(6.8*age);
            
            new CalorieIntake(calc).setVisible(true);
        }else if(gender.equals("Female")){
            calc = 655 + (4.35 * weightlbs) + (4.7 * fHeight) - (4.7 * age);
            new CalorieIntake(calc).setVisible(true);
        }
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bmr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   
}
